export default {
    name: 'machinery',
    title: 'Machinery',
    visibleIf:
        '["Planting", "Spraying", "Tillage", "Harvest"] contains {purpose}',
    elements: [
        {
            name: 'machinery-operator',
            title: 'Operator',
            type: 'text',
            autocomplete: 'previous',
            autofill: 'lastused',
        },
        {
            name: 'machinery-spray-or-spread',
            visibleIf: '{purpose} == "Spraying"',
            title: 'Spray or Spread',
            type: 'radiogroup',
            choices: ['Spraying', 'Spreading'],
        },
        {
            name: 'machinery-pull-type',
            visibleIf: '{purpose} == "Spraying"',
            title: 'Pull Type',
            type: 'radiogroup',
            choices: ['Pull', 'Self-Propelled'],
        },
        {
            name: 'machinery-makemodel',
            // TODO: change title based on operation?
            title: 'Machine Make and Model',
            type: 'dropdown',
            hideIfChoicesEmpty: false,
            hasOther: true,
            storeOthersAsComment: false,
            otherText: 'Add new make and model',
            otherErrorText: 'Please enter the new make and model',
            autocomplete: 'previous',
            autofill: 'lastused',
            choices: [
                // TODO: Have default choices from a secondary sheet?
            ],
        },
        {
            name: 'planter-makemodel',
            visibleIf: '{purpose} == "Planting"',
            title: 'Planter Make and Model',
            type: 'dropdown',
            hideIfChoicesEmpty: false,
            hasOther: true,
            storeOthersAsComment: false,
            otherText: 'Add new make and model',
            otherErrorText: 'Please enter the new make and model',
            autocomplete: 'previous',
            autofill: 'lastused',
            choices: [
                // TODO: Have default choices from a secondary sheet?
            ],
        },
        {
            name: 'planter-num-rows',
            visibleIf: '{purpose} == "Planting"',
            title: 'Number of Planter Rows',
            type: 'text',
            inputType: 'number',
            autofill: 'lastused',
        },
        {
            name: 'machinery-implement',
            title: 'Implement',
            type: 'panel',
            elements: [
                {
                    name: 'machinery-implement-type',
                    visibleIf: '{purpose} == "Tillage"',
                    title: 'Type',
                    type: 'dropdown',
                    hasOther: true,
                    storeOthersAsComment: false,
                    otherText: 'Add new type',
                    otherErrorText: 'Please enter the new type',
                    autofill: 'lastused',
                    autocomplete: 'previous',
                },
                {
                    name: 'machinery-implement-makemodel',
                    visibleIf:
                        '{purpose} == "Tillage" or {machinery-pull-type} == "Self-Propelled"',
                    title: 'Make and Model',
                    type: 'dropdown',
                    hideIfChoicesEmpty: false,
                    hasOther: true,
                    storeOthersAsComment: false,
                    otherText: 'Add new make and model',
                    otherErrorText: 'Please enter the new make and model',
                    autofill: 'lastused',
                    autocomplete: 'previous',
                },
            ],
        },
        {
            name: 'machinery-calibration-report',
            visibleIf: '{purpose} == "Planting"',
            title: 'Calibration Report',
            type: 'text',
        },
        {
            name: 'machinery-row-width',
            visibleIf: '{purpose} == "Planting"',
            title: 'Row Width (ft)',
            type: 'text',
            inputType: 'number',
            placeHolder: '3 ft',
            autofill: 'lastused',
        },
        {
            name: 'machinery-width',
            visibleIf: '["Spraying", "Tillage"] contains {purpose}',
            title: 'Width (ft)',
            type: 'text',
            inputType: 'number',
            placeHolder: '30 ft',
            autofill: 'lastused',
        },
        {
            name: 'machinery-hearder-width',
            visibleIf: '{purpose} == "Harvest"',
            title: 'Header Width (ft or rows)',
            type: 'text',
            inputType: 'number',
            placeHolder: '30 ft',
            autofill: 'lastused',
        },
        {
            name: 'machinery-sprayer-type',
            visibleIf: '{purpose} == "Spraying"',
            title: 'Type',
            type: 'dropdown',
            autofill: 'lastused',
            choices: ['Nozzles', 'Drop Tube', 'Spinner'],
        },
        {
            name: 'machinery-rate',
            visibleIf: '{purpose} == "Spraying"',
            title: 'Rate',
            type: 'text',
        },
        {
            name: 'machinery-speed',
            title: 'Speed (mph)',
            type: 'text',
            inputType: 'number',
            placeHolder: '15 mph',
        },
        {
            name: 'machinery-depth',
            visibleIf: '["Planting", "Tillage"] contains {purpose}',
            title: 'Depth (in)',
            type: 'text',
            inputType: 'number',
            placeHolder: '1.5 in',
        },
        {
            name: 'machinery-yield-mapped',
            visibleIf: '{purpose} == "Harvest"',
            title: 'Yield Mapped?',
            type: 'boolean',
        },
        {
            name: 'machinery-yield-calibrated',
            visibleIf: '{purpose} == "Harvest"',
            title: 'Yield Monitor Calibrated?',
            type: 'boolean',
        },
        {
            name: 'machinery-controller-makemodel',
            visibleIf: '["Planting", "Spraying"] contains {purpose}',
            title: 'Controller Make and Model',
            type: 'dropdown',
            hideIfChoicesEmpty: false,
            hasOther: true,
            storeOthersAsComment: false,
            otherText: 'Add new make and model',
            otherErrorText: 'Please enter the new make and model',
            autocomplete: 'previous',
            autofill: 'lastused',
            choices: [
                // TODO: Have default choices from a secondary sheet?
            ],
        },
        {
            name: 'machinery-variable-rate',
            visibleIf: '{purpose} == "Spraying"',
            title: 'Variable Rate?',
            type: 'boolean',
        },
        {
            name: 'machinery-variable-rate-source',
            visibleIf:
                '{purpose} == "Spraying" and {machinery-variable-rate} == true',
            title: 'Variable Rate Source',
            type: 'text',
            autocomplete: 'previous',
        },
    ],
};
